//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4337
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsJSON
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string E_Mail { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    }
}
